### ISSUE TITLE
Comparison to MViTv2

### ISSUE THREAD

**Issue by JunweiLiang** [hunto/LightViT#2]
Hi authors,

Thanks for sharing the work. Just curious: how does the compare to a recent [MViTv2 work](https://arxiv.org/pdf/2112.01526.pdf) in terms of FLOPs/accuracy trade-off?

Thanks,
Junwei

**Comment by hunto** [comment]
Hi @JunweiLiang,

Thanks for your attentions about our work. Since LightViT mainly focuses on the light-weight models, we only have architecture variants with a largest FLOPs of 3.9G (LightViT-B). In contrast, the smallest network in MViTv2 variants is with 4.7G FLOPs (MViTv2-T). Therefore, we cannot directly compare the FLOPs-accuracy trade-off in these two papers. Maybe we will develop some variants of LightViT with larger FLOPs, so that it would be better to compare LightViT with other ViTs.
